server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /products {
        proxy_pass http://product-service:8004;
    }

    location /orders {
        proxy_pass http://order-service:8001;
    }

    location /payments {
        proxy_pass http://payment-service:8002;
    }

    location /payment {
        proxy_pass http://payment-service:8002;
    }

    location /notifications {
        proxy_pass http://notification-service:8003;
    }
}
