server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /products {
        proxy_pass http://host.docker.internal:18081;
    }

    location /orders {
        proxy_pass http://host.docker.internal:18081;
    }

    location /payments {
        proxy_pass http://host.docker.internal:18081;
    }

    location /payment {
        proxy_pass http://host.docker.internal:18081;
    }

    location /notifications {
        proxy_pass http://host.docker.internal:18081;
    }
}
